Task/reorganized structure of project
AnatoliRub/rs-angular-itransition pull request #5
Opened 2022-01-17 12:24 UTC by AnatoliRub

Change structure of the project

2022-01-17 13:01 UTC, StanevichIvan requested changes

2022-01-17 13:01 UTC, StanevichIvan commented on youtube-client/src/app/youtube/pages/detailed-page/detailed-page.component.html
> +        This Is KuJi Podcast. In this issue, Timur karginov, Andrey Konyaev and Nurlan Saburov
Where from comes this text. If we need it might we could create a file with this string.

2022-01-20 09:47 UTC, AnatoliRub commented on youtube-client/src/app/youtube/components/info-item/info-item.component.ts
> +  @Input() count = '';
The data that comes from the file has string type and should be used in this type.

2022-01-20 09:54 UTC, AnatoliRub commented on youtube-client/src/app/youtube/pages/detailed-page/detailed-page.component.html
> +        This Is KuJi Podcast. In this issue, Timur karginov, Andrey Konyaev and Nurlan Saburov
This text should be comes from file with data on this stage. I fix it when I implement routing and when I'll have access to the post data.

2022-01-20 10:25 UTC, AnatoliRub commented on youtube-client/src/app/youtube/components/info/info.component.ts
> +  @Input() statistics: Statistic | undefined = undefined;
a550391

2022-01-20 10:25 UTC, AnatoliRub commented on youtube-client/src/app/youtube/components/info/info.component.html
> +  <app-info-item [count]="statistics!.viewCount">
a550391

2022-01-20 10:26 UTC, AnatoliRub commented on youtube-client/src/app/auth/pages/login-page/login-page.component.ts
> +      firstName: new FormControl('', [
I improve it on the next stage.

2022-01-20 18:16 UTC, merged